name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      matrix:
        version:
          - '1.6'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
        include:
          - version: '1'
            os: macOS-latest
            arch: x64
          - version: '1'
            os: windows-latest
            arch: x64
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          coverage: ${{ matrix.os == 'ubuntu-latest' && matrix.version == '1' }}
      - uses: julia-actions/julia-processcoverage@v1
        if: matrix.os == 'ubuntu-latest' && matrix.version == '1'
      - uses: codecov/codecov-action@v3
        if: matrix.os == 'ubuntu-latest' && matrix.version == '1'
        with:
          file: lcov.info
      - uses: coverallsapp/github-action@v2
        if: matrix.os == 'ubuntu-latest' && matrix.version == '1'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info
