name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.3'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
        include:
          - version: '1'
            os: macOS-latest
            arch: x64
          - version: '1'
            os: windows-latest
            arch: x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          coverage: ${{ matrix.os == 'ubuntu-latest' && matrix.version == '1' }}
      - uses: julia-actions/julia-processcoverage@v1
        if: matrix.os == 'ubuntu-latest' && matrix.version == '1'
      - uses: codecov/codecov-action@v2
        if: matrix.os == 'ubuntu-latest' && matrix.version == '1'
        with:
          file: lcov.info
      - uses: coverallsapp/github-action@master
        if: matrix.os == 'ubuntu-latest' && matrix.version == '1'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info
